---
- name: Prepare Host for tf-ansible-deployer
  hosts: all
  become: true

  tasks:
    - name: Ensure apt directories exist
      ansible.builtin.file:
        path: /var/lib/apt/lists/partial
        state: directory
        mode: '0755'

    - name: Update apt cache safely
      ansible.builtin.apt:
        update_cache: yes

    - name: Ensure .ssh directory exists and has correct permissions
      ansible.builtin.file:
        path: "/root/.ssh"
        state: directory
        mode: '0700'

    - name: Add public key to authorized_keys
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - libdbus-1-dev
          - pkg-config
          - libglib2.0-dev
          - cmake
          - build-essential
        state: present
        update_cache: yes

    - name: Recreate clean kolla virtualenv (no system packages)
      ansible.builtin.command: >
        python3 -m venv /opt/kollaenv
      args:
        creates: /opt/kollaenv/bin/activate

    - name: Install required python packages for kolla
      ansible.builtin.pip:
        name:
          - docker==5.0.3
          - requests==2.31.0
          - urllib3==1.26.18
          - dbus-python
        virtualenv: /opt/kollaenv
